version: "3.8"

services:
  postgresql:
    container_name: postgresql
    image: postgres:alpine
    ports:
      - "54321:5432"
    volumes:
      - ./initdb/db.sql:/docker-entrypoint-initdb.d/db.sql
      - ./initdb/dbdata:/data/postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ordersDB
      PG_DATA: /data/postgres

  stan:
    container_name: stanserver
    image: nats-streaming:alpine
    ports:
      - "4223:4222"
      - "8223:8222"
    command:
      - "--store"
      - "file"
      - "--dir"
      - "data"
